<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.0.1" />
    <PackageReference Include="MediatR" Version="13.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Backend.Domain\Backend.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Film\" />
    <Folder Include="Features\Person\Handlers\Commands\" />
    <Folder Include="Features\Person\Requests\Common\" />
    <Folder Include="Features\Vehicle\" />
    <Folder Include="Features\Starship\" />
    <Folder Include="Features\Species\" />
    <Folder Include="Features\Planet\" />
  </ItemGroup>

</Project>
